version: '3.8'
services:
  zookeeper-reinaldi:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  postgres-reinaldi:
    image: postgres
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=learning_reactive_r2dbc
    ports:
      - "5432:5432"
  mongodb-reinaldi:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=learning_reactive_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
  redis-reinaldi:
    image: 'redis:latest'
    ports:
      - "6379:6379"
  kafka-reinaldi:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-reinaldi:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper-reinaldi
  api-reinaldi:
    environment:
      - APPLICATION_PORT=8083
      - POSTGRES_USER=postgresql
      - POSTGRES_PASS=postgresql
      - POSTGRES_HOST=postgres-reinaldi
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=learning_reactive_r2dbc
      - MONGO_USER=mongodb
      - MONGO_PASS=mongodb
      - MONGO_HOST=mongodb-reinaldi:27017
      - MONGO_DB_NAME=learning_reactive_mongo
      - REDIS_HOST=redis-reinaldi
      - REDIS_PORT=6379
      - KAFKA_HOST=kafka-reinaldi:9092
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    build: .
    ports:
      - "8083:8083"
      - "5005:5005"
    depends_on:
      - postgres-reinaldi
      - mongodb-reinaldi
      - redis-reinaldi
      - kafka-reinaldi