spring:
  profiles:
    active: local  # por defecto usa `application-local.yml`
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false  # recomendado si usás Kafka reactivo

server:
  reactive:
    session:
      timeout: 70s

kafka:
  topics:
    retry-exhausted: CR_RETRY_EXHAUSTED
    cc-evaluation: CC_EVALUATION_EVENTS
  groups:
    retry-exhausted: retry-exhausted-group
    cc-evaluation: cc-evaluation-group
external:
  api:
    base-url: http://localhost:8084/external-api
    percentage: /percentage
