server:
  port: 8084
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    properties:
      security:
        protocol: PLAINTEXT
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:postgres-reinaldi}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:learning_reactive_r2dbc}?connectTimeout=30&socketTimeout=30
    username: ${POSTGRES_USER:postgresql}
    password: ${POSTGRES_PASS:postgresql}
    locations: classpath:db/migration
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASS:admin}@${MONGO_HOST:localhost}/${MONGO_DB_NAME:learning}?authSource=admin
      database: ${MONGO_DB_NAME:learning}
      uuid-representation: standard
      auto-index-creation: true